artifactId=pub.frmw.ApplicationComponents_aac.verify.sigstore
contentsModel=self-contained
description=Sigstore package verification provider for Algites Application Components in specified technologies
documentation.generatedAt=2026-09-24T02:06:19Z
documentation.sourceCommit=67bd57fbd5b0298bdd5e16e718b7431f056e06bf
documentation.sourceRef=main
gradleProjectPath=:aac:verify:sigstore
groupId=
localArtifactId=aac.verify.sigstore
name=AAC Sigstore Package Verifier
path=aac/verify/sigstore
python.distributionName=algites-pub-frmw-applicationcomponents-aac-verify-sigstore
python.importNamespace=algites.pub.frmw.applicationcomponents.aac.verify.sigstore
python.version=1.0.dev20260924020342163
structureKind=artifact
technologyKinds=python
version.lane=1
version.qualifierKind=SNAPSHOT
version.qualifierLabel=SNAPSHOT
version.resolvedValue=1.0-SNAPSHOT
version.revision=0
