artifactId=pub.frmw.ApplicationComponents_aac.verify.sigstore
contentsModel=self-contained
description=Sigstore package verification provider for Algites Application Components in specified technologies
documentation.generatedAt=2026-09-21T09:48:46Z
documentation.sourceCommit=725a649c8cb4b450e81aa6061dae83623971d2b7
documentation.sourceRef=main
gradleProjectPath=:aac:verify:sigstore
groupId=
localArtifactId=aac.verify.sigstore
name=AAC Sigstore Package Verifier
path=aac/verify/sigstore
python.distributionName=algites-pub-frmw-applicationcomponents-aac-verify-sigstore
python.importNamespace=algites.pub.frmw.applicationcomponents.aac.verify.sigstore
python.version=1.0.dev0
structureKind=artifact
technologyKinds=python
version.lane=1
version.qualifierKind=SNAPSHOT
version.qualifierLabel=SNAPSHOT
version.resolvedValue=1.0-SNAPSHOT
version.revision=0
