artifactId=pub.frmw.Aac_aac.verify.sigstore
contentsModel=self-contained
description=Sigstore package verification provider for Algites Application
documentation.generatedAt=2026-09-30T22:02:55Z
documentation.sourceCommit=830e9788f386d9dc040f212b5c021b7a87a605e1
documentation.sourceRef=main
gradleProjectPath=:aac:verify:sigstore
groupId=eu.algites.frmw.aac
localArtifactId=aac.verify.sigstore
name=AAC Sigstore Package Verifier
path=aac/verify/sigstore
python.distributionName=eu-algites-pub-frmw-aac-aac-verify-sigstore
python.importNamespace=algites.pub.frmw.aac.aac.verify.sigstore
python.version=1.0.dev20260930215808812
structureKind=artifact
technologyKinds=python
version.lane=
version.qualifierKind=snapshot
version.resolvedValue=1.0-SNAPSHOT
version.revision=0
