from __future__ import annotations
from dataclasses import dataclass, field
from enum import Enum
from typing import Mapping
from ..capability.api import AInConsumerCardinality
from ..descriptor.api import AIcCapabilityEntitlementDescriptor, AIcEntitlementLicensingScopeDescriptor
from ..presentation.api import AIcDisplayText
from ..packages.api import AIcPackageSidecar

from .aic_catalog_query import AIcCatalogQuery
from .aic_catalog_publisher import AIcCatalogPublisher
from .aic_catalog_icon import AIcCatalogIcon
from .aic_catalog_capability_offer import AIcCatalogCapabilityOffer
from .aic_catalog_capability_requirement import AIcCatalogCapabilityRequirement
from .ain_catalog_persistent_schema_kind import AInCatalogPersistentSchemaKind
from .aic_catalog_persistent_schema import AIcCatalogPersistentSchema
from .aic_catalog_artifact_locator import AIcCatalogArtifactLocator
from .aic_catalog_artifact import AIcCatalogArtifact
from .aic_catalog_release import AIcCatalogRelease
from .aic_catalog_component import AIcCatalogComponent
from .aic_catalog_document import AIcCatalogDocument
from .aic_catalog_entry import AIcCatalogEntry
from .aic_catalog_source_registration import AIcCatalogSourceRegistration
from .aic_catalog_bootstrap import AIcCatalogBootstrap
