from __future__ import annotations
from dataclasses import dataclass, field
from enum import Enum
from typing import Mapping

from .ain_persistence_transaction_phase import AInPersistenceTransactionPhase
from .aic_persistence_transaction_read import AIcPersistenceTransactionRead
from .aic_persistence_transaction_write import AIcPersistenceTransactionWrite
from .aic_persistence_transaction_descriptor import AIcPersistenceTransactionDescriptor
