from __future__ import annotations
from dataclasses import dataclass, field
from typing import Mapping

from .aic_authorization_principal import AIcAuthorizationPrincipal
from .aic_authorization_request import AIcAuthorizationRequest
from .aic_authorization_decision import AIcAuthorizationDecision
from .aic_component_authorization_grant import AIcComponentAuthorizationGrant
