from __future__ import annotations
from dataclasses import dataclass, field
from enum import Enum
from typing import Mapping
from ..presentation.api import AIcDisplayText

from .ain_consumer_cardinality import AInConsumerCardinality
from .aic_capability_group import AIcCapabilityGroup
from .aic_capability_ref import AIcCapabilityRef
from .aic_provided_capability import AIcProvidedCapability
from .aic_authorization_permission_descriptor import AIcAuthorizationPermissionDescriptor
from .aic_operation_authorization_requirement import AIcOperationAuthorizationRequirement
from .ain_capability_operation_interaction_kind import AInCapabilityOperationInteractionKind
from .aic_schema_ref import AIcSchemaRef
from .aic_capability_operation_interaction import AIcCapabilityOperationInteraction
from .aic_capability_operation import AIcCapabilityOperation
from .aic_capability_contract import AIcCapabilityContract
