artifactId=pub.frmw.ApplicationComponents_aac.uiqt
contentsModel=self-contained
description=Administration UI implementation for AAC in specified technologies (PySide6 for python)
documentation.generatedAt=2026-09-21T11:36:11Z
documentation.sourceCommit=0cd0c171a46f1c392e5002b16104d19820355590
documentation.sourceRef=main
gradleProjectPath=:aac:uiqt
groupId=
localArtifactId=aac.uiqt
name=Algites Application Components Qt UI
path=aac/uiqt
python.distributionName=algites-pub-frmw-applicationcomponents-aac-uiqt
python.importNamespace=algites.pub.frmw.applicationcomponents.aac.uiqt
python.version=not tied to a concrete package build
structureKind=artifact
technologyKinds=python
version.lane=1
version.qualifierKind=SNAPSHOT
version.qualifierLabel=SNAPSHOT
version.resolvedValue=1.0-SNAPSHOT
version.revision=0
