from __future__ import annotations
from abc import ABC, abstractmethod
from typing import Mapping

from .aii_data_entity_get_record_1 import AIiDataEntityGetRecord_1
from .aii_data_entity_query_records_1 import AIiDataEntityQueryRecords_1
from .aii_data_entity_apply_direct_record_changes_1 import AIiDataEntityApplyDirectRecordChanges_1
from .aii_data_entity_inspect_storage_support_1 import AIiDataEntityInspectStorageSupport_1
from .aii_data_entity_ensure_storage_support_1 import AIiDataEntityEnsureStorageSupport_1
from .aii_data_entity_retire_storage_support_1 import AIiDataEntityRetireStorageSupport_1
from .aii_data_entity_create_storage_backup_1 import AIiDataEntityCreateStorageBackup_1
from .aii_data_entity_inspect_storage_backup_1 import AIiDataEntityInspectStorageBackup_1
from .aii_data_entity_restore_storage_backup_1 import AIiDataEntityRestoreStorageBackup_1
