artifactId=pub.frmw.Aac_aac.verify.sigstore
contentsModel=self-contained
description=Sigstore package verification provider for Algites Application
documentation.generatedAt=2026-09-30T02:55:36Z
documentation.sourceCommit=85099f4f7c5872faf28a204e9b341d350fe66b81
documentation.sourceRef=main
gradleProjectPath=:aac:verify:sigstore
groupId=eu.algites.frmw.aac
localArtifactId=aac.verify.sigstore
name=AAC Sigstore Package Verifier
path=aac/verify/sigstore
python.distributionName=eu-algites-pub-frmw-aac-aac-verify-sigstore
python.importNamespace=algites.pub.frmw.aac.aac.verify.sigstore
python.version=
structureKind=artifact
technologyKinds=python
version.lane=
version.qualifierKind=snapshot
version.resolvedValue=
version.revision=0
