artifactId=pub.frmw.Aac_devtools.aacbuilding
contentsModel=self-contained
description=Repository development, verification and build tools
documentation.generatedAt=2026-09-30T02:55:36Z
documentation.sourceCommit=85099f4f7c5872faf28a204e9b341d350fe66b81
documentation.sourceRef=main
gradleProjectPath=:devtools:aacbuilding
groupId=eu.algites.frmw.aac
localArtifactId=devtools.aacbuilding
name=AAC Development Tools
path=devtools/aacbuilding
python.distributionName=eu-algites-pub-frmw-aac-devtools-aacbuilding
python.importNamespace=algites.pub.frmw.aac.devtools.aacbuilding
python.version=
structureKind=artifact
technologyKinds=python
version.lane=
version.qualifierKind=snapshot
version.resolvedValue=
version.revision=0
