from enum import Enum


class AInStateResultDeliveryMode(str, Enum):
    ON_DEMAND_COMPLETE = "ON_DEMAND_COMPLETE"
    ON_DEMAND_DELTA = "ON_DEMAND_DELTA"
    ON_CHANGE_COMPLETE = "ON_CHANGE_COMPLETE"
    ON_CHANGE_DELTA = "ON_CHANGE_DELTA"
    ALWAYS_COMPLETE = "ALWAYS_COMPLETE"
