from __future__ import annotations
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import Callable, Generic, Mapping, TypeVar
from ..presentation.api import AIcDisplayText
from ..interaction_types import AInStateResultDeliveryMode

from .ain_operation_execution_state import AInOperationExecutionState
from .ain_operation_interaction_event_type import AInOperationInteractionEventType
from .ain_operation_interaction_severity import AInOperationInteractionSeverity
from .ain_operation_interaction_mode import AInOperationInteractionMode
from .ain_operation_interaction_detail_level import AInOperationInteractionDetailLevel
from .ain_operation_interaction_failure_detail_level import AInOperationInteractionFailureDetailLevel
from .aic_operation_interaction_event import AIcOperationInteractionEvent
from .aic_operation_interaction_features import AIcOperationInteractionFeatures
from .aic_operation_interaction_provider_to_caller_message import AIcOperationInteractionProviderToCallerMessage
from .aic_operation_interaction_caller_to_provider_message import AIcOperationInteractionCallerToProviderMessage
from .aic_operation_failure import AIcOperationFailure
from .aix_capability_operation_failed import AIxCapabilityOperationFailed
from .aii_operation_failure_exception_factory import AIiOperationFailureExceptionFactory
from .aic_callable_operation_failure_exception_factory import AIcCallableOperationFailureExceptionFactory
from .aix_operation_cancelled import AIxOperationCancelled
from .aii_operation_interaction_provider_to_caller import AIiOperationInteractionProviderToCaller
from .aii_operation_interaction_caller_to_provider import AIiOperationInteractionCallerToProvider
from .aic_null_operation_interaction import AIcNullOperationInteraction

AIxOperationFailureT = TypeVar("AIxOperationFailureT", bound=AIxCapabilityOperationFailed)
