from __future__ import annotations
from dataclasses import dataclass, field
from enum import Enum
from typing import Mapping
from ..presentation.api import AIcDisplayText
from ..capability.api import AIcProvidedCapability, AInConsumerCardinality
from ..instances.api import AInProviderAccessMode
from ..interaction_types import AInStateResultDeliveryMode
from ..readiness.api import AIcReadinessRequirementDescriptor

from .ain_component_origin import AInComponentOrigin
from .ain_provider_runtime_profile import AInProviderRuntimeProfile
from .ain_data_entity_access import AInDataEntityAccess
from .aic_schema_migration_step_descriptor import AIcSchemaMigrationStepDescriptor
from .aic_persisted_schema_descriptor import AIcPersistedSchemaDescriptor
from .aic_provider_runtime_descriptor import AIcProviderRuntimeDescriptor
from .aic_initial_provider_instance_descriptor import AIcInitialProviderInstanceDescriptor
from .aic_consumer_requirement_descriptor import AIcConsumerRequirementDescriptor
from .aic_operation_parameter_enum_value_descriptor import AIcOperationParameterEnumValueDescriptor
from .aic_operation_parameter_definition_descriptor import AIcOperationParameterDefinitionDescriptor
from .aic_capability_provider_operation_interaction_descriptor import AIcCapabilityProviderOperationInteractionDescriptor
from .aic_capability_provider_operation_descriptor import AIcCapabilityProviderOperationDescriptor
from .aic_provider_implementation_class_descriptor import AIcProviderImplementationClassDescriptor
from .aic_provider_definition_descriptor import AIcProviderDefinitionDescriptor
from .aic_entitlement_licensing_scope_descriptor import AIcEntitlementLicensingScopeDescriptor
from .aic_permission_descriptor import AIcPermissionDescriptor
from .aic_capability_entitlement_descriptor import AIcCapabilityEntitlementDescriptor
from .aic_data_entity_requirement_descriptor import AIcDataEntityRequirementDescriptor
from .aic_data_entity_support_descriptor import AIcDataEntitySupportDescriptor
from .aic_lifecycle_hooks_descriptor import AIcLifecycleHooksDescriptor
from .aic_component_descriptor import AIcComponentDescriptor
