artifactId=pub.frmw.ApplicationComponents_aac.uiqt
contentsModel=self-contained
description=Administration UI implementation for AAC in specified technologies (PySide6 for python)
documentation.generatedAt=2026-09-22T13:01:27Z
documentation.sourceCommit=9b135c6d93e5f8185ec41b4d1457d862cfc4f857
documentation.sourceRef=main
gradleProjectPath=:aac:uiqt
groupId=
localArtifactId=aac.uiqt
name=Algites Application Components Qt UI
path=aac/uiqt
python.distributionName=algites-pub-frmw-applicationcomponents-aac-uiqt
python.importNamespace=algites.pub.frmw.applicationcomponents.aac.uiqt
python.version=1.0.dev20260922125858696
structureKind=artifact
technologyKinds=python
version.lane=1
version.qualifierKind=SNAPSHOT
version.qualifierLabel=SNAPSHOT
version.resolvedValue=1.0-SNAPSHOT
version.revision=0
