from __future__ import annotations
from dataclasses import dataclass
from enum import Enum
from ..descriptor.api import AIcSchemaMigrationStepDescriptor

from .ain_schema_runtime_interpretation import AInSchemaRuntimeInterpretation
from .ain_persistence_convergence_status import AInPersistenceConvergenceStatus
from .ain_persistence_convergence_attempt_status import AInPersistenceConvergenceAttemptStatus
from .aic_schema_compatibility_assessment import AIcSchemaCompatibilityAssessment
