artifactId=pub.frmw.ApplicationComponents_aac.coreimpl
contentsModel=self-contained
description=Reusable implementations of the Algites Application Components runtime in specified technologies
documentation.generatedAt=2026-09-24T02:06:19Z
documentation.sourceCommit=67bd57fbd5b0298bdd5e16e718b7431f056e06bf
documentation.sourceRef=main
gradleProjectPath=:aac:coreimpl
groupId=
localArtifactId=aac.coreimpl
name=Algites Application Components Core Implementation
path=aac/coreimpl
python.distributionName=algites-pub-frmw-applicationcomponents-aac-coreimpl
python.importNamespace=algites.pub.frmw.applicationcomponents.aac.coreimpl
python.version=1.0.dev20260924020342163
structureKind=artifact
technologyKinds=python
version.lane=1
version.qualifierKind=SNAPSHOT
version.qualifierLabel=SNAPSHOT
version.resolvedValue=1.0-SNAPSHOT
version.revision=0
