artifactId=pub.frmw.Aac_components.dataentity.yamlfsdes
contentsModel=self-contained
description=YAML file-system implementation of AAC generic Data Entity
documentation.generatedAt=2026-10-01T12:57:40Z
documentation.sourceCommit=830e9788f386d9dc040f212b5c021b7a87a605e1
documentation.sourceRef=main
gradleProjectPath=:components:dataentity:yamlfsdes
groupId=eu.algites.frmw.aac
localArtifactId=components.dataentity.yamlfsdes
name=Algites Application Components YAML File-System Data Entity Storage
path=components/dataentity/yamlfsdes
python.distributionName=eu-algites-pub-frmw-aac-components-dataentity-yamlfsdes
python.importNamespace=algites.pub.frmw.aac.components.dataentity.yamlfsdes
python.version=1.0.dev20261001125251579
structureKind=artifact
technologyKinds=python
version.lane=
version.qualifierKind=snapshot
version.resolvedValue=1.0-SNAPSHOT
version.revision=0
