artifactId=pub.frmw.ApplicationComponents_components.dataentity.yamlfsdes
contentsModel=self-contained
description=YAML file-system implementation of AAC generic Data Entity storage capabilities
documentation.generatedAt=2026-09-25T02:23:07Z
documentation.sourceCommit=bb9725317b9fa646e9e24b16d1fe21677972715d
documentation.sourceRef=main
gradleProjectPath=:components:dataentity:yamlfsdes
groupId=
localArtifactId=components.dataentity.yamlfsdes
name=Algites Application Components YAML File-System Data Entity Storage
path=components/dataentity/yamlfsdes
python.distributionName=algites-pub-frmw-applicationcomponents-components-dataentity-yamlfsdes
python.importNamespace=algites.pub.frmw.applicationcomponents.components.dataentity.yamlfsdes
python.version=1.0.dev20260925022045366
structureKind=artifact
technologyKinds=python
version.lane=1
version.qualifierKind=SNAPSHOT
version.qualifierLabel=SNAPSHOT
version.resolvedValue=1.0-SNAPSHOT
version.revision=0
