artifactId=pub.frmw.Aac_devtools.generators.aaccodegen
contentsModel=self-contained
description=Public shared generators for canonical AAC capability and Data
documentation.generatedAt=2026-09-30T02:55:36Z
documentation.sourceCommit=85099f4f7c5872faf28a204e9b341d350fe66b81
documentation.sourceRef=main
gradleProjectPath=:devtools:generators:aaccodegen
groupId=eu.algites.frmw.aac
localArtifactId=devtools.generators.aaccodegen
name=Algites AAC Code Generator
path=devtools/generators/aaccodegen
python.distributionName=eu-algites-pub-frmw-aac-devtools-generators-aaccodegen
python.importNamespace=algites.pub.frmw.aac.devtools.generators.aaccodegen
python.version=
structureKind=artifact
technologyKinds=python
version.lane=
version.qualifierKind=snapshot
version.resolvedValue=
version.revision=0
