artifactId=pub.frmw.Aac_aac.uiqt
contentsModel=self-contained
description=Administration UI implementation for AAC in specified
documentation.generatedAt=2026-09-30T02:55:36Z
documentation.sourceCommit=85099f4f7c5872faf28a204e9b341d350fe66b81
documentation.sourceRef=main
gradleProjectPath=:aac:uiqt
groupId=eu.algites.frmw.aac
localArtifactId=aac.uiqt
name=Algites Application Components Qt UI
path=aac/uiqt
python.distributionName=eu-algites-pub-frmw-aac-aac-uiqt
python.importNamespace=algites.pub.frmw.aac.aac.uiqt
python.version=
structureKind=artifact
technologyKinds=python
version.lane=
version.qualifierKind=snapshot
version.resolvedValue=
version.revision=0
