artifactId=pub.frmw.Aac_components.dataentity.yamlfsdes
contentsModel=self-contained
description=YAML file-system implementation of AAC generic Data Entity
documentation.generatedAt=2026-09-30T02:55:36Z
documentation.sourceCommit=85099f4f7c5872faf28a204e9b341d350fe66b81
documentation.sourceRef=main
gradleProjectPath=:components:dataentity:yamlfsdes
groupId=eu.algites.frmw.aac
localArtifactId=components.dataentity.yamlfsdes
name=Algites Application Components YAML File-System Data Entity Storage
path=components/dataentity/yamlfsdes
python.distributionName=eu-algites-pub-frmw-aac-components-dataentity-yamlfsdes
python.importNamespace=algites.pub.frmw.aac.components.dataentity.yamlfsdes
python.version=
structureKind=artifact
technologyKinds=python
version.lane=
version.qualifierKind=snapshot
version.resolvedValue=
version.revision=0
